changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - question
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - Semver-Major
    - title: Features
      labels:
        - enhancement
        - feature
        - type: feature
    - title: Fixes
      labels:
        - bug
        - fix
        - type: bug
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
